import os
import dotenv

dotenv.load_dotenv()



APP_NAME = os.getenv("APP_NAME")
DEV = bool(os.getenv("DEV"))
APP_URL = os.getenv("APP_URL")
FRONTEND_URL = os.getenv("FRONTEND_URL")
STORAGE_DIR = os.getenv("STORAGE_DIR")




JWT_SECRET = os.getenv("JWT_SECRET")
CSRF_SECRET = os.getenv("CSRF_SECRET")
REFRESH_TOKEN_PEPPER = os.getenv("REFRESH_TOKEN_PEPPER")
AFFISE_DATA_SECRET = os.getenv("AFFISE_DATA_SECRET")
REFRESH_COOKIE_PATH = os.getenv("REFRESH_COOKIE_PATH")
ACCESS_TOKEN_EXPIRE_SECONDS = int(os.getenv("ACCESS_TOKEN_EXPIRE_SECONDS"))
REFRESH_TOKEN_EXPIRE_SECONDS = int(os.getenv("REFRESH_TOKEN_EXPIRE_SECONDS"))





POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_DB = os.getenv("POSTGRES_DB")


ADB_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
SDB_URL = f"postgresql+psycopg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"


REDIS_URL = os.getenv("REDIS_URL")


MAIL_FROM_ADDRESS = os.getenv("MAIL_FROM_ADDRESS")
MAIL_FROM_NAME = os.getenv("MAIL_FROM_NAME")
MAIL_TRANSPORT = os.getenv("MAIL_TRANSPORT")




AFFISE_ENABLED = bool(os.getenv("AFFISE_ENABLED"))
AFFISE_API_URL = os.getenv("AFFISE_API_URL")
AFFISE_API_KEY = os.getenv("AFFISE_API_KEY")


TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
TELEGRAM_LOG_LEVEL = os.getenv("TELEGRAM_LOG_LEVEL")
#
